#%RAML 1.0
title: API specification

documentation: 
  - !include Documentation/documentation.raml

/organization:
  post:
    headers:
      UserID:
        description: the identifier for the user who posts a new organization
        type: !include DataType/user.raml
        example: !include Examples/user.raml
    body:
      application/json:
        type: !include DataType/user.raml
  get:
    description: Returns an organization entity.
    responses:
      201:
        body:
          application/json:
            type: !include DataType/org.raml
            example: !include Examples/org.raml

